// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA7KhpCJ-__0AbBzM9BwbBT81_HvXhTj8',
    appId: '1:304638735634:web:a012e4bb33e1ca7615afcb',
    messagingSenderId: '304638735634',
    projectId: 'movie-plus-192b9',
    authDomain: 'movie-plus-192b9.firebaseapp.com',
    databaseURL: 'https://movie-plus-192b9-default-rtdb.firebaseio.com',
    storageBucket: 'movie-plus-192b9.appspot.com',
    measurementId: 'G-2XN2BJD2PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR28FnUEG_xv3H9bpSApIO5KmDZJlXV0w',
    appId: '1:304638735634:android:abab5e4441d0c24615afcb',
    messagingSenderId: '304638735634',
    projectId: 'movie-plus-192b9',
    databaseURL: 'https://movie-plus-192b9-default-rtdb.firebaseio.com',
    storageBucket: 'movie-plus-192b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA28r2XyjHj2F7cZkNpWESR1FIzHA21yYY',
    appId: '1:304638735634:ios:fe408dba5e3c38a715afcb',
    messagingSenderId: '304638735634',
    projectId: 'movie-plus-192b9',
    databaseURL: 'https://movie-plus-192b9-default-rtdb.firebaseio.com',
    storageBucket: 'movie-plus-192b9.appspot.com',
    iosBundleId: 'dev.erkinov.moviePlusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA28r2XyjHj2F7cZkNpWESR1FIzHA21yYY',
    appId: '1:304638735634:ios:d787ae3ac1424f3915afcb',
    messagingSenderId: '304638735634',
    projectId: 'movie-plus-192b9',
    databaseURL: 'https://movie-plus-192b9-default-rtdb.firebaseio.com',
    storageBucket: 'movie-plus-192b9.appspot.com',
    iosBundleId: 'dev.erkinov.moviePlusApp.RunnerTests',
  );
}
